name: Dynatrace Monaco Deploy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'manifest.yaml'
      - 'projects/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'manifest.yaml'
      - 'projects/**'

jobs:
  monaco:
    runs-on: ubuntu-latest

    env:
      # Dynatrace token from GitHub Secrets 👇
      DT_API_TOKEN: ${{ secrets.DT_API_TOKEN }}
      # adjust if your tenant changes
      DT_ENV: my-dt-env

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Monaco
        run: |
          MONACO_VERSION=2.26.1
          curl -L https://github.com/Dynatrace/Dynatrace-Configuration-as-Code/releases/download/v${MONACO_VERSION}/monaco-linux-amd64.zip -o monaco.zip
          sudo apt-get update -y
          sudo apt-get install -y unzip
          unzip monaco.zip -d monaco-bin
          sudo mv monaco-bin/monaco /usr/local/bin/monaco
          monaco version

      # 1) On PRs → do only dry-run
      - name: Dry-run deploy (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: .
        run: |
          monaco deploy --dry-run manifest.yaml

      # 2) On push to main → do actual deploy
      - name: Deploy to Dynatrace (main)
        if: ${{ github.event_name == 'push' }}
        working-directory: .
        run: |
          monaco deploy manifest.yaml
