name: Dynatrace Monaco Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  monaco:
    runs-on: ubuntu-latest
    env:
      DT_API_TOKEN: ${{ secrets.DT_API_TOKEN }}
      DT_ENV: my-dt-env

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Monaco
        run: |
          MONACO_VERSION=2.26.1
          curl -L https://github.com/Dynatrace/Dynatrace-Configuration-as-Code/releases/download/v${MONACO_VERSION}/monaco-linux-amd64.zip -o monaco.zip
          sudo apt-get update -y
          sudo apt-get install -y unzip
          unzip monaco.zip -d monaco-bin
          sudo mv monaco-bin/monaco /usr/local/bin/monaco
          monaco version

      # PR = dry run
      - name: Dry-run deploy (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        run: monaco deploy --dry-run manifest.yaml

      # Push to main/master = real deploy
      - name: Deploy to Dynatrace (push)
        if: ${{ github.event_name == 'push' }}
        run: monaco deploy manifest.yaml
